from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
import time
driver = webdriver.Chrome(r"C:\Users\Kedareesh G A\Downloads\chromedriver_win32\chromedriver.exe")
driver.get("http://localhost:8069/web/login")
print(driver.title)

def update_form_field(driver, field_name, field_value, step):
	search_bar = driver.find_element(By.NAME, field_name)
	search_bar.clear()	
	time.sleep(3)
	search_bar.send_keys(field_value)
	print("Kedareesh: Step%s passed" %step)
	time.sleep(3)

driver.get("http://localhost:8069/web/login")
print("Kedareesh: Step1 passed")

update_form_field(driver, "login", "kedareesh@csu.fullerton.edu", 2)
update_form_field(driver, "password", "Kedareesh@1234", 3)
driver.find_element(By.NAME, "login").send_keys(Keys.RETURN)
time.sleep(3)
print(driver.current_url)

driver.get("http://localhost:8069/web#cids=1&menu_id=268&action=382&model=hospital.patient&view_type=form")
print("Kedareesh: Step3 passed")
time.sleep(3)
update_form_field(driver, "name", "Jack Leo", 4)
dropdown = driver.find_element_by_name("gender")
dd = Select(dropdown)
dd.select_by_visible_text("Male")
time.sleep(3)
dd.select_by_visible_text("Female")
time.sleep(3)
dd.select_by_visible_text("Other")
time.sleep(3)
dd.select_by_visible_text("Male")
dropdown = driver.find_element_by_id("o_field_input_11")
time.sleep(3)
dropdown.send_keys("abc")
time.sleep(3)
update_form_field(driver, "note", "Emergency", 5)
update_form_field(driver, "age", "26", 6)
save_button = driver.find_element(by=By.XPATH, value="/html/body/div[1]/div/div[1]/div[2]/div[1]/div/div/div[2]/button[1]")
save_button.click()
time.sleep(3)

driver.get("http://localhost:8069/web#cids=1&menu_id=268&action=384&model=hospital.doctor&view_type=kanban")
time.sleep(3)
driver.get("http://localhost:8069/web#cids=1&menu_id=268&action=384&model=hospital.doctor&view_type=form")
time.sleep(3)
update_form_field(driver, "doctor_name", "Oliver Jake", 7)
dropdown = driver.find_element_by_name("gender")
dd = Select(dropdown)
dd.select_by_visible_text("Male")
time.sleep(3)
dd.select_by_visible_text("Female")
time.sleep(3)
dd.select_by_visible_text("Other")
time.sleep(3)
dd.select_by_visible_text("Female")
time.sleep(3)
update_form_field(driver, "age", "44", 8)
update_form_field(driver, "note", "Cardiologists - Wrok from 10am to 7pm PST", 9)
save_button = driver.find_element(by=By.XPATH, value="/html/body/div[1]/div/div[1]/div[2]/div[1]/div/div/div[2]/button[1]")
save_button.click()
time.sleep(5)
Edit_button = driver.find_element(by=By.XPATH, value="/html/body/div[1]/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/button[1]")
Edit_button.click()
update_form_field(driver, "note", "Cardiologists - Work from 10am to 7pm PST & Week off on Saturday & Sunday", 10)
time.sleep(3)
save_button = driver.find_element(by=By.XPATH, value="/html/body/div[1]/div/div[1]/div[2]/div[1]/div/div/div[2]/button[1]")
save_button.click()
print(driver.current_url)
time.sleep(10)
driver.close()